### Create User
POST http://localhost:4000/api/users HTTP/1.1
Accept: application/json

{
  "name": "John Smith",
  "age": 39,
  "hobbies": [ "coding",  "mountain climbing", "yachting"]
}

### Get User
GET http://localhost:4000/api/users/the-user-id-here HTTP/1.1


### Get ALL Users
GET http://localhost:4000/api/users HTTP/1.1


### Update User
PUT http://localhost:4000/api/users/the-user-id-here HTTP/1.1
Accept: application/json

{
  "name": "John Smith Jr",
  "age": 20,
  "hobbies": ["gaming", "yachting"]
}

### Delete User
DELETE http://localhost:4000/api/users/the-user-id-here HTTP/1.1


### Get bad route
GET http://localhost:4000/no-such-route HTTP/1.1
Accept: application/json
